# Generated by Django 5.2.17 on 2026-09-15 21:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "catalogue",
            "0005_remove_recordingcontribution_contribution_valid_role_and_more",
        ),
        ("media_assets", "0007_first_radio_metadata_confirmation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="opprettet"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="sist endret"),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preparing", "Forbereder"),
                            ("ready", "Klar"),
                            ("partial", "Delvis"),
                            ("failed", "Kan ikke leveres"),
                            ("expired", "Artefakt utløpt"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "profile",
                    models.CharField(
                        choices=[
                            ("internal_complete", "Intern – komplett"),
                            ("external_radio", "Ekstern radio"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("internal", "Intern bruk"),
                            ("broadcast", "Kringkasting"),
                            ("archive", "Arkivarbeid"),
                            ("rightsholder", "Levering til artist/rettighetshaver"),
                            ("distribution", "Distribusjonsrelatert arbeid"),
                            ("other", "Annet"),
                        ],
                        max_length=30,
                    ),
                ),
                ("purpose_description", models.TextField(blank=True)),
                ("retain_for_future_use", models.BooleanField(default=False)),
                ("other_use", models.BooleanField(default=False)),
                ("other_use_description", models.TextField(blank=True)),
                ("recipient_name", models.CharField(max_length=255)),
                (
                    "recipient_organization",
                    models.CharField(blank=True, max_length=255),
                ),
                ("manifest_snapshot", models.JSONField(blank=True, default=list)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
                "permissions": [
                    ("create_delivery", "Kan opprette leveranse"),
                    ("download_delivery", "Kan laste ned leveranse"),
                    ("create_external_delivery", "Kan opprette ekstern leveranse"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DeliveryArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="opprettet"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="sist endret"),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("transformed_flac", "Transformert FLAC"),
                            ("zip", "ZIP-arkiv"),
                        ],
                        max_length=30,
                    ),
                ),
                ("relative_path", models.CharField(max_length=500)),
                ("filename", models.CharField(max_length=255)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField()),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="delivery.delivery",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="DeliveryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="opprettet"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="sist endret"),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "Klar"),
                            ("skipped", "Hoppet over"),
                            ("failed", "Feilet"),
                        ],
                        max_length=20,
                    ),
                ),
                ("output_filename", models.CharField(blank=True, max_length=255)),
                ("recording_uuid_snapshot", models.UUIDField()),
                ("title_snapshot", models.CharField(max_length=500)),
                ("artist_snapshot", models.CharField(blank=True, max_length=500)),
                ("isrc_snapshot", models.CharField(blank=True, max_length=30)),
                ("source_asset_uuid_snapshot", models.UUIDField(blank=True, null=True)),
                ("source_sha256_snapshot", models.CharField(blank=True, max_length=64)),
                ("delivered_metadata", models.JSONField(blank=True, default=dict)),
                ("message", models.CharField(blank=True, max_length=500)),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="delivery.delivery",
                    ),
                ),
                (
                    "recording",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_items",
                        to="catalogue.recording",
                    ),
                ),
                (
                    "source_file_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_items",
                        to="media_assets.fileasset",
                    ),
                ),
                (
                    "source_file_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_items",
                        to="media_assets.filelocation",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="DownloadEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="opprettet"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="sist endret"),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("requested", "Nedlasting forespurt"),
                            ("served", "Nedlasting servert"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_events",
                        to="delivery.delivery",
                    ),
                ),
                (
                    "delivery_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_events",
                        to="delivery.deliveryitem",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="deliveryitem",
            constraint=models.UniqueConstraint(
                fields=("delivery", "recording"), name="delivery_one_item_per_recording"
            ),
        ),
    ]
