# Generated by Django 5.2.17 on 2026-09-12 14:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "revision",
                    models.PositiveBigIntegerField(default=1, editable=False),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Person, organization or group name; not a rights ownership assertion.",
                        max_length=255,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("person", "Person"),
                            ("organization", "Organization"),
                            ("group", "Group"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Parties",
                "ordering": ("name", "id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("kind__in", ["person", "organization", "group"])
                        ),
                        name="party_valid_kind",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("name", ""), _negated=True),
                        name="party_nonempty_name",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ArtistIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "revision",
                    models.PositiveBigIntegerField(default=1, editable=False),
                ),
                ("display_name", models.CharField(max_length=255)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="artist_identities",
                        to="parties.party",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Artist identities",
                "ordering": ("display_name", "id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("display_name", ""), _negated=True
                        ),
                        name="artist_nonempty_name",
                    )
                ],
            },
        ),
    ]
