# Generated by Django 5.2.17 on 2026-09-12 17:59

import rights_core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="artistidentity",
            name="artist_nonempty_name",
        ),
        migrations.RemoveConstraint(
            model_name="party",
            name="party_nonempty_name",
        ),
        migrations.AlterField(
            model_name="artistidentity",
            name="display_name",
            field=models.CharField(
                max_length=255,
                validators=[rights_core.models.validate_not_blank],
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="name",
            field=models.CharField(
                help_text="Person, organization or group name; not a rights ownership assertion.",
                max_length=255,
                validators=[rights_core.models.validate_not_blank],
            ),
        ),
        migrations.AddConstraint(
            model_name="artistidentity",
            constraint=models.CheckConstraint(
                condition=models.Q(("display_name__regex", ".*\\S.*")),
                name="artist_nonblank_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="party",
            constraint=models.CheckConstraint(
                condition=models.Q(("name__regex", ".*\\S.*")),
                name="party_nonblank_name",
            ),
        ),
    ]
