# Generated by Django 5.2.17 on 2026-09-13 11:22

import django.db.models.deletion
import rights_core.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "parties",
            "0002_remove_artistidentity_artist_nonempty_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artistidentity",
            options={
                "ordering": ("display_name", "id"),
                "verbose_name": "artistidentitet",
                "verbose_name_plural": "artistidentiteter",
            },
        ),
        migrations.AlterModelOptions(
            name="party",
            options={
                "ordering": ("name", "id"),
                "verbose_name": "person/organisasjon",
                "verbose_name_plural": "personer og organisasjoner",
            },
        ),
        migrations.AlterField(
            model_name="artistidentity",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="opprettet"
            ),
        ),
        migrations.AlterField(
            model_name="artistidentity",
            name="display_name",
            field=models.CharField(
                max_length=255,
                validators=[rights_core.models.validate_not_blank],
                verbose_name="artistnavn",
            ),
        ),
        migrations.AlterField(
            model_name="artistidentity",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="permanent UUID",
            ),
        ),
        migrations.AlterField(
            model_name="artistidentity",
            name="party",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="artist_identities",
                to="parties.party",
                verbose_name="person/organisasjon",
            ),
        ),
        migrations.AlterField(
            model_name="artistidentity",
            name="revision",
            field=models.PositiveBigIntegerField(
                default=1, editable=False, verbose_name="revisjon"
            ),
        ),
        migrations.AlterField(
            model_name="artistidentity",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="sist endret"
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="opprettet"
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="permanent UUID",
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="kind",
            field=models.CharField(
                choices=[
                    ("person", "Person"),
                    ("organization", "Organisasjon"),
                    ("group", "Gruppe"),
                ],
                max_length=20,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="name",
            field=models.CharField(
                help_text="Navnet på personen, organisasjonen eller gruppen. Navnet dokumenterer ikke eierskap.",
                max_length=255,
                validators=[rights_core.models.validate_not_blank],
                verbose_name="navn",
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="revision",
            field=models.PositiveBigIntegerField(
                default=1, editable=False, verbose_name="revisjon"
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="sist endret"
            ),
        ),
    ]
