# Generated by Django 5.2.17 on 2026-09-13 17:08

import django.db.models.deletion
import rights_core.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0004_duplicatecandidate_label_release_releasetrack_and_more"),
        ("media_assets", "0002_filelocation_verification_status_and_more"),
        ("parties", "0003_alter_artistidentity_options_alter_party_options_and_more"),
        ("provenance", "0002_appliedmetadatachange"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agreement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="opprettet"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="sist endret"),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=500,
                        validators=[rights_core.models.validate_not_blank],
                        verbose_name="tittel",
                    ),
                ),
                (
                    "internal_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="intern referanse"
                    ),
                ),
                (
                    "agreement_type",
                    models.CharField(
                        choices=[
                            ("transfer", "Overdragelse"),
                            ("license", "Lisens"),
                            ("administration", "Administrasjonsavtale"),
                            ("distribution", "Distribusjonsavtale"),
                            ("other", "Annen avtale"),
                        ],
                        max_length=30,
                        verbose_name="avtaletype",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="virkningsdato"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="utløpsdato"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Utkast"),
                            ("active", "Aktiv"),
                            ("expired", "Utløpt"),
                            ("terminated", "Avsluttet"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="merknader")),
            ],
            options={
                "verbose_name": "avtale",
                "verbose_name_plural": "avtaler",
                "ordering": ("title", "id"),
                "permissions": (("manage_agreement", "Kan administrere avtaler"),),
            },
        ),
        migrations.CreateModel(
            name="Territory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="opprettet"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="sist endret"),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="ISO 3166-1 alfa-2, for eksempel NO, SE eller DK.",
                        max_length=2,
                        unique=True,
                        verbose_name="ISO-landkode",
                    ),
                ),
                (
                    "name_nb",
                    models.CharField(
                        max_length=100,
                        validators=[rights_core.models.validate_not_blank],
                        verbose_name="norsk navn",
                    ),
                ),
            ],
            options={
                "verbose_name": "territorium",
                "verbose_name_plural": "territorier",
                "ordering": ("name_nb", "code"),
            },
        ),
        migrations.CreateModel(
            name="AgreementDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="opprettet"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="sist endret"),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="beskrivelse"
                    ),
                ),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_links",
                        to="rights.agreement",
                        verbose_name="avtale",
                    ),
                ),
                (
                    "file_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agreement_links",
                        to="media_assets.fileasset",
                        verbose_name="dokumentfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "avtaledokument",
                "verbose_name_plural": "avtaledokumenter",
            },
        ),
        migrations.AddField(
            model_name="agreement",
            name="documents",
            field=models.ManyToManyField(
                related_name="rights_agreements",
                through="rights.AgreementDocument",
                to="media_assets.fileasset",
            ),
        ),
        migrations.CreateModel(
            name="AgreementParty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="opprettet"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="sist endret"),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("assignor", "Overdrager"),
                            ("assignee", "Mottaker"),
                            ("licensor", "Lisensgiver"),
                            ("licensee", "Lisenshaver"),
                            ("distributor", "Distributør"),
                            ("administrator", "Administrator"),
                            ("other", "Annen rolle"),
                        ],
                        max_length=30,
                        verbose_name="rolle",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="merknad"
                    ),
                ),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="party_roles",
                        to="rights.agreement",
                        verbose_name="avtale",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agreement_roles",
                        to="parties.party",
                        verbose_name="part",
                    ),
                ),
            ],
            options={
                "verbose_name": "avtalepart",
                "verbose_name_plural": "avtaleparter",
                "ordering": ("agreement", "role", "party"),
            },
        ),
        migrations.AddField(
            model_name="agreement",
            name="parties",
            field=models.ManyToManyField(
                related_name="rights_agreements",
                through="rights.AgreementParty",
                to="parties.party",
            ),
        ),
        migrations.CreateModel(
            name="RightsClaim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="opprettet"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="sist endret"),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "right_type",
                    models.CharField(
                        choices=[
                            ("master_ownership", "Mastereierskap"),
                            ("master_administration", "Administrasjon"),
                            ("distribution", "Distribusjon"),
                        ],
                        max_length=30,
                        verbose_name="rettighetstype",
                    ),
                ),
                (
                    "share",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="andel i prosent",
                    ),
                ),
                (
                    "territory_mode",
                    models.CharField(
                        choices=[
                            ("world", "Hele verden"),
                            ("include", "Bare angitte territorier"),
                            ("exclude", "Hele verden unntatt angitte territorier"),
                        ],
                        default="world",
                        max_length=20,
                        verbose_name="territorieomfang",
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(blank=True, null=True, verbose_name="gyldig fra"),
                ),
                (
                    "valid_until",
                    models.DateField(blank=True, null=True, verbose_name="gyldig til"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unverified", "Importert / ikke verifisert"),
                            ("confirmed", "Bekreftet"),
                            ("disputed", "Bestridt"),
                            ("rejected", "Avvist"),
                            ("superseded", "Erstattet"),
                        ],
                        default="unverified",
                        editable=False,
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="merknader")),
                (
                    "agreement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rights_claims",
                        to="rights.agreement",
                        verbose_name="avtale",
                    ),
                ),
                (
                    "grantor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rights_granted_claims",
                        to="parties.party",
                        verbose_name="rettighetsgiver",
                    ),
                ),
                (
                    "recording",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rights_claims",
                        to="catalogue.recording",
                        verbose_name="innspilling",
                    ),
                ),
                (
                    "rights_holder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rights_held_claims",
                        to="parties.party",
                        verbose_name="rettighetshaver",
                    ),
                ),
                (
                    "source_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rights_claims",
                        to="provenance.sourcerecord",
                        verbose_name="kildepost",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="rights.rightsclaim",
                        verbose_name="erstatter krav",
                    ),
                ),
            ],
            options={
                "verbose_name": "rettighetskrav",
                "verbose_name_plural": "rettighetskrav",
                "ordering": ("recording", "right_type", "status", "rights_holder"),
                "permissions": (("decide_rightsclaim", "Kan beslutte rettighetskrav"),),
            },
        ),
        migrations.CreateModel(
            name="ClaimTerritory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="opprettet"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="sist endret"),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="territory_links",
                        to="rights.rightsclaim",
                        verbose_name="rettighetskrav",
                    ),
                ),
                (
                    "territory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claim_links",
                        to="rights.territory",
                        verbose_name="territorium",
                    ),
                ),
            ],
            options={
                "verbose_name": "kravterritorium",
                "verbose_name_plural": "kravterritorier",
            },
        ),
        migrations.CreateModel(
            name="RightsConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="opprettet"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="sist endret"),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "singleton",
                    models.BooleanField(default=True, editable=False, unique=True),
                ),
                (
                    "local_organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="local_rights_configuration",
                        to="parties.party",
                        verbose_name="lokal organisasjon",
                    ),
                ),
            ],
            options={
                "verbose_name": "rettighetsinnstilling",
                "verbose_name_plural": "rettighetsinnstillinger",
            },
        ),
        migrations.CreateModel(
            name="RightsDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="opprettet"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="sist endret"),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("confirmed", "Bekreftet"),
                            ("disputed", "Bestridt"),
                            ("rejected", "Avvist"),
                            ("superseded", "Erstattet"),
                            ("documented", "Dokumentasjon oppdatert"),
                        ],
                        max_length=20,
                        verbose_name="beslutning",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="begrunnelse")),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="rights.rightsclaim",
                        verbose_name="rettighetskrav",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rights_decisions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="besluttet av",
                    ),
                ),
            ],
            options={
                "verbose_name": "rettighetsbeslutning",
                "verbose_name_plural": "rettighetsbeslutninger",
                "ordering": ("-created_at", "id"),
            },
        ),
        migrations.AddField(
            model_name="rightsclaim",
            name="territories",
            field=models.ManyToManyField(
                blank=True,
                related_name="rights_claims",
                through="rights.ClaimTerritory",
                to="rights.territory",
            ),
        ),
        migrations.AddConstraint(
            model_name="agreementdocument",
            constraint=models.UniqueConstraint(
                fields=("agreement", "file_asset"),
                name="rights_agreement_unique_document",
            ),
        ),
        migrations.AddConstraint(
            model_name="agreementparty",
            constraint=models.UniqueConstraint(
                fields=("agreement", "party", "role"),
                name="rights_agreement_party_unique_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="agreement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("internal_reference", ""), _negated=True),
                fields=("internal_reference",),
                name="rights_agreement_unique_reference",
            ),
        ),
        migrations.AddConstraint(
            model_name="agreement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("expiry_date__isnull", True),
                    ("effective_date__isnull", True),
                    ("expiry_date__gte", models.F("effective_date")),
                    _connector="OR",
                ),
                name="rights_agreement_valid_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="rightsconfiguration",
            constraint=models.CheckConstraint(
                condition=models.Q(("singleton", True)),
                name="rights_configuration_singleton",
            ),
        ),
        migrations.AddIndex(
            model_name="rightsclaim",
            index=models.Index(
                fields=["recording", "right_type", "status"],
                name="rights_claim_summary_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rightsclaim",
            index=models.Index(
                fields=["rights_holder", "right_type"], name="rights_claim_holder_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rightsclaim",
            index=models.Index(
                fields=["valid_from", "valid_until"], name="rights_claim_period_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="rightsclaim",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("share__isnull", True),
                    models.Q(
                        ("share__gte", Decimal("0")), ("share__lte", Decimal("100"))
                    ),
                    _connector="OR",
                ),
                name="rights_claim_share_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="rightsclaim",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_until__isnull", True),
                    ("valid_from__isnull", True),
                    ("valid_until__gte", models.F("valid_from")),
                    _connector="OR",
                ),
                name="rights_claim_valid_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="claimterritory",
            constraint=models.UniqueConstraint(
                fields=("claim", "territory"), name="rights_claim_unique_territory"
            ),
        ),
    ]
