# Generated by Django 5.2.17 on 2026-09-17 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalogue",
            "0005_remove_recordingcontribution_contribution_valid_role_and_more",
        ),
        (
            "parties",
            "0003_alter_artistidentity_options_alter_party_options_and_more",
        ),
        ("provenance", "0002_appliedmetadatachange"),
        ("rights", "0003_rightsclaim_evidence_strength"),
    ]

    operations = [
        migrations.AddField(
            model_name="rightsclaim",
            name="release_scope",
            field=models.ForeignKey(
                blank=True,
                help_text="Tomt betyr generell innspillingsrett innenfor øvrig scope.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scoped_rights_claims",
                to="catalogue.release",
                verbose_name="rettighet avgrenset til utgivelse",
            ),
        ),
        migrations.AddConstraint(
            model_name="rightsclaim",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("release_scope__isnull", True),
                    (
                        "right_type__in",
                        ("master_administration", "distribution"),
                    ),
                    _connector="OR",
                ),
                name="rights_release_scope_type",
            ),
        ),
    ]
