# Generated by Django 5.2.17 on 2026-09-13 20:25

import django.db.models.deletion
import media_assets.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "catalogue",
            "0005_remove_recordingcontribution_contribution_valid_role_and_more",
        ),
        ("media_assets", "0003_filechecksum_and_more"),
        ("provenance", "0002_appliedmetadatachange"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FlacIngestBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="opprettet"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="sist endret"
                    ),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "relative_root",
                    models.CharField(
                        default=".",
                        max_length=1000,
                        validators=[media_assets.models.validate_logical_path],
                        verbose_name="valgt mappe",
                    ),
                ),
                (
                    "recursive",
                    models.BooleanField(
                        default=True, verbose_name="inkluder undermapper"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preview", "Forhåndsvisning klar"),
                            ("partial", "Delvis brukt"),
                            ("applied", "Brukt"),
                        ],
                        default="preview",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flac_ingest_batches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="opprettet av",
                    ),
                ),
                (
                    "import_batch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flac_ingest",
                        to="provenance.importbatch",
                        verbose_name="provenancebatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "FLAC-innlesing",
                "verbose_name_plural": "FLAC-innlesinger",
                "ordering": ("-created_at", "id"),
                "permissions": (
                    (
                        "apply_flacingestbatch",
                        "Kan bruke FLAC-forhåndsvisning",
                    ),
                ),
            },
        ),
        migrations.CreateModel(
            name="FlacSyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="opprettet"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="sist endret"
                    ),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("success", "Synkronisert"),
                            ("missing", "Fil ikke funnet"),
                            ("conflict", "Konflikt"),
                            ("failed", "Feilet"),
                        ],
                        max_length=20,
                        verbose_name="resultat",
                    ),
                ),
                (
                    "written_tags",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="skrevne katalogtags",
                    ),
                ),
                (
                    "protected_tags",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="bevarte radiotags",
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="feil")),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sync_logs",
                        to="media_assets.fileasset",
                        verbose_name="radio-FLAC",
                    ),
                ),
            ],
            options={
                "verbose_name": "FLAC-synkroniseringslogg",
                "verbose_name_plural": "FLAC-synkroniseringslogger",
                "ordering": ("-created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="FlacIngestItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="opprettet"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="sist endret"
                    ),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "relative_path",
                    models.CharField(
                        max_length=1000,
                        validators=[media_assets.models.validate_logical_path],
                        verbose_name="relativ filsti",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("new", "Ny innspilling"),
                            ("matched", "Eksisterende treff"),
                            ("unchanged", "Uendret fil"),
                            ("conflict", "Må kontrolleres"),
                            ("invalid", "Kan ikke leses"),
                        ],
                        max_length=20,
                        verbose_name="forslag",
                    ),
                ),
                (
                    "match_method",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="treffgrunnlag"
                    ),
                ),
                (
                    "raw_tags",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="alle råtags"
                    ),
                ),
                (
                    "parsed_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="tolkede metadata",
                    ),
                ),
                (
                    "technical_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="tekniske lydopplysninger",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="filstørrelse"
                    ),
                ),
                (
                    "source_modified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fil endret"
                    ),
                ),
                (
                    "sha256",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="SHA-256"
                    ),
                ),
                (
                    "candidates",
                    models.JSONField(
                        blank=True, default=list, verbose_name="mulige treff"
                    ),
                ),
                (
                    "messages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="kontrollmeldinger",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="brukt"
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="flac_ingest.flacingestbatch",
                        verbose_name="innlesing",
                    ),
                ),
                (
                    "file_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flac_ingest_items",
                        to="media_assets.fileasset",
                    ),
                ),
                (
                    "recording",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flac_ingest_items",
                        to="catalogue.recording",
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flac_ingest_items",
                        to="catalogue.release",
                    ),
                ),
                (
                    "release_track",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flac_ingest_items",
                        to="catalogue.releasetrack",
                    ),
                ),
                (
                    "source_record",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flac_ingest_item",
                        to="provenance.sourcerecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "FLAC-fil i forhåndsvisning",
                "verbose_name_plural": "FLAC-filer i forhåndsvisning",
                "ordering": ("relative_path", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("batch", "relative_path"),
                        name="flac_batch_unique_path",
                    )
                ],
            },
        ),
    ]
