# Generated by Django 5.2.17 on 2026-09-13 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flac_ingest", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="flacingestitem",
            name="review_note",
            field=models.TextField(blank=True, verbose_name="kontrollmerknad"),
        ),
        migrations.AddField(
            model_name="flacingestitem",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="kontrollert"
            ),
        ),
        migrations.AddField(
            model_name="flacingestitem",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviewed_flac_ingest_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="kontrollert av",
            ),
        ),
    ]
