# Generated by Django 5.2.17 on 2026-09-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flac_ingest', '0002_flacingestitem_review_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flacingestitem',
            name='action',
            field=models.CharField(choices=[('new', 'Ny innspilling'), ('matched', 'Eksisterende treff'), ('updated', 'Endret fil'), ('unchanged', 'Uendret fil'), ('retry', 'Prøv igjen'), ('conflict', 'Må kontrolleres'), ('invalid', 'Kan ikke leses')], max_length=20, verbose_name='forslag'),
        ),
    ]
