# Generated by Django 5.2.17 on 2026-09-13 12:29

import catalogue.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0004_duplicatecandidate_label_release_releasetrack_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MusicLibraryEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="opprettet"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="sist endret"),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="sjanger"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        validators=[catalogue.validators.validate_language],
                        verbose_name="språk",
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("general", "Alle"),
                            ("children", "Barn"),
                            ("youth", "Ungdom"),
                            ("adult", "Voksne"),
                            ("family", "Familie"),
                        ],
                        max_length=20,
                        verbose_name="målgruppe",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        blank=True,
                        help_text="Kontrollert kanalnavn eller kode når kjent.",
                        max_length=100,
                        verbose_name="kanal",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("female", "Kvinne"),
                            ("male", "Mann"),
                            ("mixed", "Blandet"),
                            ("other", "Annet / ikke relevant"),
                        ],
                        max_length=20,
                        verbose_name="kjønn",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Skala 1–5.",
                        null=True,
                        verbose_name="rating",
                    ),
                ),
                (
                    "energy",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Skala 1–5.",
                        null=True,
                        verbose_name="energi",
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("unverified", "Importert / ikke verifisert"),
                            ("confirmed", "Bekreftet"),
                            ("disputed", "Bestridt"),
                            ("rejected", "Avvist"),
                            ("superseded", "Erstattet"),
                        ],
                        default="unverified",
                        max_length=20,
                        verbose_name="verifikasjonsstatus",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="merknader")),
                (
                    "recording",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="music_library_entry",
                        to="catalogue.recording",
                        verbose_name="innspilling",
                    ),
                ),
            ],
            options={
                "verbose_name": "musikkarkivpost",
                "verbose_name_plural": "musikkarkiv",
                "ordering": ("recording__title", "id"),
                "indexes": [
                    models.Index(fields=["genre"], name="library_genre_idx"),
                    models.Index(fields=["channel"], name="library_channel_idx"),
                    models.Index(
                        fields=["verification_status"], name="library_verify_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("rating__isnull", True),
                            models.Q(("rating__gte", 1), ("rating__lte", 5)),
                            _connector="OR",
                        ),
                        name="library_rating_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("energy__isnull", True),
                            models.Q(("energy__gte", 1), ("energy__lte", 5)),
                            _connector="OR",
                        ),
                        name="library_energy_range",
                    ),
                ],
            },
        ),
    ]
