# Generated by Django 5.2.17 on 2026-09-13 20:25

import django.core.validators
import django.db.models.deletion
import re
import uuid
from django.db import migrations, models

MIGRATION_NAMESPACE = uuid.UUID("6d06c746-2e37-4e76-99b5-16bde1392221")
TARGET_NAMES = {
    "general": "Alle",
    "children": "Barn",
    "youth": "Ungdom",
    "adult": "Voksne",
    "family": "Familie",
}


def _uuid(kind, value):
    return uuid.uuid5(MIGRATION_NAMESPACE, f"{kind}:{value}")


def _code(value):
    code = re.sub(r"[^a-z0-9]+", "_", value.casefold()).strip("_")
    return (code or "verdi")[:50]


def _available_code(model, value):
    base = _code(value)
    code = base
    number = 2
    while model.objects.filter(code=code).exists():
        suffix = f"_{number}"
        code = f"{base[: 50 - len(suffix)]}{suffix}"
        number += 1
    return code


def migrate_radio_fields(apps, schema_editor):
    Entry = apps.get_model("music_library", "MusicLibraryEntry")
    Channel = apps.get_model("music_library", "Channel")
    Target = apps.get_model("music_library", "TargetAudience")
    ChannelLink = apps.get_model("music_library", "MusicLibraryChannel")
    TargetLink = apps.get_model("music_library", "MusicLibraryTargetAudience")

    for entry in Entry.objects.all().iterator():
        if entry.channel:
            channel = Channel.objects.filter(
                name__iexact=entry.channel
            ).first()
            if channel is None:
                channel = Channel.objects.create(
                    id=_uuid("channel", entry.channel.casefold()),
                    name=entry.channel,
                    code=_available_code(Channel, entry.channel),
                )
            ChannelLink.objects.get_or_create(
                library_entry_id=entry.pk,
                channel_id=channel.pk,
                defaults={
                    "id": _uuid("channel-link", f"{entry.pk}:{channel.pk}")
                },
            )
        if entry.target:
            target_name = TARGET_NAMES.get(entry.target, entry.target)
            target, _ = Target.objects.get_or_create(
                code=_code(entry.target),
                defaults={
                    "id": _uuid("target", entry.target),
                    "name": target_name,
                },
            )
            TargetLink.objects.get_or_create(
                library_entry_id=entry.pk,
                target_audience_id=target.pk,
                defaults={
                    "id": _uuid("target-link", f"{entry.pk}:{target.pk}")
                },
            )
        if entry.rating is not None:
            if entry.energy is None:
                entry.energy = entry.rating
            elif entry.energy != entry.rating:
                audit_note = f"Historisk fase-2-rating før Energy-migrasjon: {entry.rating}."
                entry.notes = f"{entry.notes.rstrip()}\n{audit_note}".strip()
            entry.save(update_fields=("energy", "notes"))


def reverse_radio_fields(apps, schema_editor):
    Entry = apps.get_model("music_library", "MusicLibraryEntry")
    for entry in Entry.objects.all().iterator():
        channel = (
            entry.channels.order_by("name")
            .values_list("name", flat=True)
            .first()
        )
        target = (
            entry.target_audiences.order_by("code")
            .values_list("code", flat=True)
            .first()
        )
        entry.channel = channel or ""
        entry.target = target or ""
        entry.rating = entry.energy
        entry.save(update_fields=("channel", "target", "rating"))


class Migration(migrations.Migration):

    dependencies = [
        ("music_library", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="opprettet"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="sist endret"
                    ),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Bruk små bokstaver, tall, bindestrek eller understrek i koden.",
                                regex="^[a-z0-9][a-z0-9_-]*$",
                            )
                        ],
                        verbose_name="kode",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="navn"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="aktiv"),
                ),
            ],
            options={
                "verbose_name": "kanal",
                "verbose_name_plural": "kanaler",
                "ordering": ("name", "id"),
            },
        ),
        migrations.CreateModel(
            name="MusicLibraryChannel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="opprettet"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="sist endret"
                    ),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
            ],
            options={
                "verbose_name": "kanalvalg",
                "verbose_name_plural": "kanalvalg",
            },
        ),
        migrations.CreateModel(
            name="MusicLibraryTargetAudience",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="opprettet"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="sist endret"
                    ),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
            ],
            options={
                "verbose_name": "målgruppevalg",
                "verbose_name_plural": "målgruppevalg",
            },
        ),
        migrations.CreateModel(
            name="TargetAudience",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="opprettet"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="sist endret"
                    ),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Bruk små bokstaver, tall, bindestrek eller understrek i koden.",
                                regex="^[a-z0-9][a-z0-9_-]*$",
                            )
                        ],
                        verbose_name="kode",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="navn"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="aktiv"),
                ),
            ],
            options={
                "verbose_name": "målgruppe",
                "verbose_name_plural": "målgrupper",
                "ordering": ("name", "id"),
            },
        ),
        migrations.AlterField(
            model_name="musiclibraryentry",
            name="energy",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="P7s energinivå 1–5. Leses fra FLAC-taggen RATING.",
                null=True,
                verbose_name="Energy",
            ),
        ),
        migrations.AddField(
            model_name="musiclibrarychannel",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="library_links",
                to="music_library.channel",
            ),
        ),
        migrations.AddField(
            model_name="musiclibrarychannel",
            name="library_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_links",
                to="music_library.musiclibraryentry",
            ),
        ),
        migrations.AddField(
            model_name="musiclibraryentry",
            name="channels",
            field=models.ManyToManyField(
                blank=True,
                related_name="library_entries",
                through="music_library.MusicLibraryChannel",
                to="music_library.channel",
                verbose_name="kanaler",
            ),
        ),
        migrations.AddField(
            model_name="musiclibrarytargetaudience",
            name="library_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target_links",
                to="music_library.musiclibraryentry",
            ),
        ),
        migrations.AddField(
            model_name="musiclibrarytargetaudience",
            name="target_audience",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="library_links",
                to="music_library.targetaudience",
            ),
        ),
        migrations.AddField(
            model_name="musiclibraryentry",
            name="target_audiences",
            field=models.ManyToManyField(
                blank=True,
                related_name="library_entries",
                through="music_library.MusicLibraryTargetAudience",
                to="music_library.targetaudience",
                verbose_name="målgrupper",
            ),
        ),
        migrations.AddConstraint(
            model_name="musiclibrarychannel",
            constraint=models.UniqueConstraint(
                fields=("library_entry", "channel"),
                name="library_unique_channel",
            ),
        ),
        migrations.AddConstraint(
            model_name="musiclibrarytargetaudience",
            constraint=models.UniqueConstraint(
                fields=("library_entry", "target_audience"),
                name="library_unique_target",
            ),
        ),
        migrations.RunPython(migrate_radio_fields, reverse_radio_fields),
        migrations.RemoveConstraint(
            model_name="musiclibraryentry",
            name="library_rating_range",
        ),
        migrations.RemoveIndex(
            model_name="musiclibraryentry",
            name="library_channel_idx",
        ),
        migrations.RemoveField(
            model_name="musiclibraryentry",
            name="channel",
        ),
        migrations.RemoveField(
            model_name="musiclibraryentry",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="musiclibraryentry",
            name="target",
        ),
    ]
