# Generated by Django 5.2.17 on 2026-09-13 23:50

import music_library.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0003_alter_musiclibraryentry_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musiclibraryentry',
            name='language',
            field=models.CharField(blank=True, max_length=64, validators=[music_library.validators.validate_radio_language], verbose_name='språk'),
        ),
    ]
