# Generated by Django 5.2.17 on 2026-09-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0004_alter_musiclibraryentry_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='musiclibraryentry',
            name='rotation_suitability',
            field=models.CharField(blank=True, choices=[('suitable', 'Rotasjonsverdig'), ('not_suitable', 'Ikke rotasjonsverdig')], help_text='Lokal vurdering av om innspillingen er egnet for rotasjon. Leses fra OneTagger/FLAC-feltet Rotasjon.', max_length=20, verbose_name='rotasjonsvurdering'),
        ),
    ]
