# Generated by Django 5.2.17 on 2026-09-12 14:17

import catalogue.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("parties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recording",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "revision",
                    models.PositiveBigIntegerField(default=1, editable=False),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "version_designation",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "recording_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sound", "Sound recording"),
                            ("video", "Music video recording"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "duration_ms",
                    models.PositiveBigIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Duration (milliseconds)",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        help_text="Optional language tag, e.g. nb or en.",
                        max_length=64,
                        validators=[catalogue.validators.validate_language],
                    ),
                ),
                (
                    "metadata_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("reviewed", "Metadata reviewed"),
                        ],
                        default="draft",
                        help_text="Describes metadata only; does not establish rights or clearance.",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ("title", "id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("title", ""), _negated=True),
                        name="recording_nonempty_title",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("metadata_status__in", ["draft", "reviewed"])
                        ),
                        name="recording_valid_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("recording_kind__in", ["", "sound", "video"])
                        ),
                        name="recording_valid_kind",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExternalIdentifier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "revision",
                    models.PositiveBigIntegerField(default=1, editable=False),
                ),
                (
                    "scheme",
                    models.CharField(
                        choices=[("ISRC", "ISRC")],
                        default="ISRC",
                        max_length=30,
                    ),
                ),
                (
                    "namespace",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ISRC is global: leave empty. Reserved for future issuer-scoped schemes.",
                        max_length=100,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Original entered value is retained; normalization is automatic.",
                        max_length=255,
                    ),
                ),
                (
                    "normalized_value",
                    models.CharField(editable=False, max_length=255),
                ),
                (
                    "recording",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identifiers",
                        to="catalogue.recording",
                    ),
                ),
            ],
            options={
                "ordering": ("scheme", "normalized_value"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scheme", "namespace", "normalized_value"),
                        name="identifier_unique_assignment",
                    ),
                    models.UniqueConstraint(
                        fields=("recording", "scheme"),
                        name="recording_one_isrc",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("namespace", ""), ("scheme", "ISRC")
                        ),
                        name="identifier_supported_scheme",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "normalized_value__regex",
                                "^[A-Z]{2}[A-Z0-9]{3}[0-9]{7}$",
                            )
                        ),
                        name="identifier_valid_isrc",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RecordingContribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "revision",
                    models.PositiveBigIntegerField(default=1, editable=False),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("primary_artist", "Primary artist"),
                            ("featured_artist", "Featured artist"),
                            ("musician", "Musician"),
                            ("vocalist", "Vocalist"),
                            ("producer", "Producer"),
                            ("engineer", "Engineer"),
                            ("conductor", "Conductor"),
                            ("choir", "Choir"),
                        ],
                        max_length=30,
                    ),
                ),
                ("credited_as", models.CharField(blank=True, max_length=255)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "artist_identity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parties.artistidentity",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recording_contributions",
                        to="parties.party",
                    ),
                ),
                (
                    "recording",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="catalogue.recording",
                    ),
                ),
            ],
            options={
                "ordering": ("display_order", "id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "role__in",
                                [
                                    "primary_artist",
                                    "featured_artist",
                                    "musician",
                                    "vocalist",
                                    "producer",
                                    "engineer",
                                    "conductor",
                                    "choir",
                                ],
                            )
                        ),
                        name="contribution_valid_role",
                    )
                ],
            },
        ),
    ]
