# Generated by Django 5.2.17 on 2026-09-12 17:59

import rights_core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="recording",
            name="recording_nonempty_title",
        ),
        migrations.AlterField(
            model_name="recording",
            name="title",
            field=models.CharField(
                max_length=500,
                validators=[rights_core.models.validate_not_blank],
            ),
        ),
        migrations.AddConstraint(
            model_name="recording",
            constraint=models.CheckConstraint(
                condition=models.Q(("title__regex", ".*\\S.*")),
                name="recording_nonblank_title",
            ),
        ),
    ]
