# Generated by Django 5.2.17 on 2026-09-13 12:29

import django.db.models.deletion
import rights_core.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0003_alter_externalidentifier_options_and_more"),
        (
            "parties",
            "0003_alter_artistidentity_options_alter_party_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DuplicateCandidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="opprettet"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="sist endret"
                    ),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "signals",
                    models.JSONField(
                        default=list,
                        help_text="Maskinlesbare grunner til mulig match.",
                        verbose_name="matchsignaler",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="matchpoeng"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Til vurdering"),
                            ("dismissed", "Avvist som dublett"),
                            ("resolved", "Løst manuelt"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="vurdering"),
                ),
            ],
            options={
                "verbose_name": "mulig dublett",
                "verbose_name_plural": "mulige dubletter",
                "ordering": ("status", "-score", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="opprettet"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="sist endret"
                    ),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        validators=[rights_core.models.validate_not_blank],
                        verbose_name="navn",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="merknader"),
                ),
            ],
            options={
                "verbose_name": "label",
                "verbose_name_plural": "labels",
                "ordering": ("name", "id"),
            },
        ),
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="opprettet"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="sist endret"
                    ),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=500,
                        validators=[rights_core.models.validate_not_blank],
                        verbose_name="tittel",
                    ),
                ),
                (
                    "release_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("lp", "LP"),
                            ("cassette", "Kassett"),
                            ("cd", "CD"),
                            ("ep", "EP"),
                            ("single", "Single"),
                            ("digital", "Digital utgivelse"),
                            ("other", "Annen"),
                        ],
                        max_length=20,
                        verbose_name="utgivelsestype",
                    ),
                ),
                (
                    "release_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="utgivelsesdato"
                    ),
                ),
                (
                    "release_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Bruk når bare året er kjent.",
                        null=True,
                        verbose_name="utgivelsesår",
                    ),
                ),
                (
                    "catalogue_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="katalognummer",
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("unverified", "Importert / ikke verifisert"),
                            ("confirmed", "Bekreftet"),
                            ("disputed", "Bestridt"),
                            ("rejected", "Avvist"),
                            ("superseded", "Erstattet"),
                        ],
                        default="unverified",
                        max_length=20,
                        verbose_name="verifikasjonsstatus",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="merknader"),
                ),
            ],
            options={
                "verbose_name": "utgivelse",
                "verbose_name_plural": "utgivelser",
                "ordering": ("title", "id"),
            },
        ),
        migrations.CreateModel(
            name="ReleaseTrack",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="opprettet"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="sist endret"
                    ),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "disc_number",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="disc/medium"
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        blank=True,
                        help_text="For eksempel A, B, C eller D.",
                        max_length=10,
                        verbose_name="side",
                    ),
                ),
                (
                    "track_number",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="spornummer"
                    ),
                ),
                (
                    "title_override",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="utgivelsesspesifikk tittel",
                    ),
                ),
                (
                    "duration_ms",
                    models.PositiveBigIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="varighet på utgivelsen (millisekunder)",
                    ),
                ),
                (
                    "sequence_number",
                    models.PositiveIntegerField(
                        help_text="Unik rekkefølge innen utgivelsen.",
                        verbose_name="sorteringsrekkefølge",
                    ),
                ),
            ],
            options={
                "verbose_name": "spor på utgivelse",
                "verbose_name_plural": "spor på utgivelser",
                "ordering": ("release", "sequence_number", "id"),
            },
        ),
        migrations.RemoveConstraint(
            model_name="externalidentifier",
            name="recording_one_isrc",
        ),
        migrations.RemoveConstraint(
            model_name="externalidentifier",
            name="identifier_supported_scheme",
        ),
        migrations.RemoveConstraint(
            model_name="externalidentifier",
            name="identifier_valid_isrc",
        ),
        migrations.AlterField(
            model_name="externalidentifier",
            name="namespace",
            field=models.CharField(
                blank=True,
                default="",
                help_text="La feltet stå tomt for ISRC og strekkoder. Oppgi systemnavn for ekstern ID.",
                max_length=100,
                verbose_name="navnerom",
            ),
        ),
        migrations.AlterField(
            model_name="externalidentifier",
            name="recording",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="identifiers",
                to="catalogue.recording",
                verbose_name="innspilling",
            ),
        ),
        migrations.AlterField(
            model_name="externalidentifier",
            name="scheme",
            field=models.CharField(
                choices=[
                    ("ISRC", "ISRC"),
                    ("UPC", "UPC"),
                    ("EAN", "EAN"),
                    ("GTIN", "GTIN"),
                    ("EXTERNAL", "Ekstern system-ID"),
                ],
                default="ISRC",
                max_length=30,
                verbose_name="type",
            ),
        ),
        migrations.AddField(
            model_name="duplicatecandidate",
            name="recording_a",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="duplicate_candidates_as_a",
                to="catalogue.recording",
                verbose_name="første innspilling",
            ),
        ),
        migrations.AddField(
            model_name="duplicatecandidate",
            name="recording_b",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="duplicate_candidates_as_b",
                to="catalogue.recording",
                verbose_name="andre innspilling",
            ),
        ),
        migrations.AddField(
            model_name="label",
            name="party",
            field=models.ForeignKey(
                blank=True,
                help_text="Valgfritt. Tilknytningen dokumenterer ikke eierskap.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="labels",
                to="parties.party",
                verbose_name="tilknyttet person/organisasjon",
            ),
        ),
        migrations.AddField(
            model_name="release",
            name="label",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="releases",
                to="catalogue.label",
                verbose_name="label",
            ),
        ),
        migrations.AddField(
            model_name="externalidentifier",
            name="release",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="identifiers",
                to="catalogue.release",
                verbose_name="utgivelse",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalidentifier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("recording__isnull", False)),
                fields=("recording", "scheme", "namespace"),
                name="recording_one_identifier_per_scheme",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalidentifier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("release__isnull", False)),
                fields=("release", "scheme", "namespace"),
                name="release_one_identifier_per_scheme",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalidentifier",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("recording__isnull", False), ("release__isnull", True)
                    ),
                    models.Q(
                        ("recording__isnull", True), ("release__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="identifier_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalidentifier",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("recording__isnull", False),
                        ("release__isnull", True),
                        ("scheme", "ISRC"),
                    ),
                    models.Q(
                        ("recording__isnull", True),
                        ("release__isnull", False),
                        ("scheme__in", ["UPC", "EAN", "GTIN"]),
                    ),
                    ("scheme", "EXTERNAL"),
                    _connector="OR",
                ),
                name="identifier_scheme_matches_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalidentifier",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("scheme", "ISRC"), _negated=True),
                    (
                        "normalized_value__regex",
                        "^[A-Z]{2}[A-Z0-9]{3}[0-9]{7}$",
                    ),
                    _connector="OR",
                ),
                name="identifier_valid_isrc",
            ),
        ),
        migrations.AddField(
            model_name="releasetrack",
            name="recording",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="release_tracks",
                to="catalogue.recording",
                verbose_name="innspilling",
            ),
        ),
        migrations.AddField(
            model_name="releasetrack",
            name="release",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracks",
                to="catalogue.release",
                verbose_name="utgivelse",
            ),
        ),
        migrations.AddConstraint(
            model_name="duplicatecandidate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("recording_a", models.F("recording_b")), _negated=True
                ),
                name="duplicate_candidate_distinct_recordings",
            ),
        ),
        migrations.AddConstraint(
            model_name="duplicatecandidate",
            constraint=models.UniqueConstraint(
                fields=("recording_a", "recording_b"),
                name="duplicate_candidate_unique_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="duplicatecandidate",
            constraint=models.CheckConstraint(
                condition=models.Q(("score__lte", 100)),
                name="duplicate_candidate_score_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="label",
            constraint=models.CheckConstraint(
                condition=models.Q(("name__regex", ".*\\S.*")),
                name="label_nonblank_name",
            ),
        ),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(
                fields=["catalogue_number"], name="release_catalogue_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(
                fields=["release_year"], name="release_year_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="release",
            constraint=models.CheckConstraint(
                condition=models.Q(("title__regex", ".*\\S.*")),
                name="release_nonblank_title",
            ),
        ),
        migrations.AddConstraint(
            model_name="release",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("release_year__isnull", True),
                    models.Q(
                        ("release_year__gte", 1800),
                        ("release_year__lte", 2200),
                    ),
                    _connector="OR",
                ),
                name="release_sensible_year",
            ),
        ),
        migrations.AddIndex(
            model_name="releasetrack",
            index=models.Index(
                fields=["release", "disc_number", "side", "track_number"],
                name="release_track_position_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="releasetrack",
            index=models.Index(
                fields=["recording"], name="release_track_recording_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="releasetrack",
            constraint=models.UniqueConstraint(
                fields=("release", "sequence_number"),
                name="release_track_unique_sequence",
            ),
        ),
        migrations.AddConstraint(
            model_name="releasetrack",
            constraint=models.CheckConstraint(
                condition=models.Q(("sequence_number__gte", 1)),
                name="release_track_positive_sequence",
            ),
        ),
    ]
