# Generated by Django 5.2.17 on 2026-09-13 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalogue",
            "0004_duplicatecandidate_label_release_releasetrack_and_more",
        ),
        (
            "parties",
            "0003_alter_artistidentity_options_alter_party_options_and_more",
        ),
        ("provenance", "0002_appliedmetadatachange"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="recordingcontribution",
            name="contribution_valid_role",
        ),
        migrations.AddField(
            model_name="recordingcontribution",
            name="source_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recording_contributions",
                to="provenance.sourcerecord",
                verbose_name="kildepost",
            ),
        ),
        migrations.AlterField(
            model_name="recordingcontribution",
            name="party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recording_contributions",
                to="parties.party",
                verbose_name="person/organisasjon",
            ),
        ),
        migrations.AlterField(
            model_name="recordingcontribution",
            name="role",
            field=models.CharField(
                choices=[
                    ("primary_artist", "Hovedartist"),
                    ("featured_artist", "Medvirkende artist"),
                    ("musician", "Musiker"),
                    ("vocalist", "Vokalist"),
                    ("producer", "Produsent"),
                    ("engineer", "Lydtekniker"),
                    ("conductor", "Dirigent"),
                    ("choir", "Kor"),
                    ("composer", "Komponist"),
                    ("lyricist", "Tekstforfatter"),
                    ("arranger", "Arrangør"),
                ],
                max_length=30,
                verbose_name="rolle",
            ),
        ),
        migrations.AddConstraint(
            model_name="recordingcontribution",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "role__in",
                        [
                            "primary_artist",
                            "featured_artist",
                            "musician",
                            "vocalist",
                            "producer",
                            "engineer",
                            "conductor",
                            "choir",
                            "composer",
                            "lyricist",
                            "arranger",
                        ],
                    )
                ),
                name="contribution_valid_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="recordingcontribution",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("party__isnull", False),
                    models.Q(("credited_as", ""), _negated=True),
                    _connector="OR",
                ),
                name="contribution_has_identity_or_credit",
            ),
        ),
    ]
