# Generated by Django 5.2.17 on 2026-09-13 12:29

import django.db.models.deletion
import media_assets.models
import rights_core.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "catalogue",
            "0004_duplicatecandidate_label_release_releasetrack_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FileAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="opprettet"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="sist endret"
                    ),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        max_length=500,
                        validators=[rights_core.models.validate_not_blank],
                        verbose_name="filnavn",
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="MIME-type/format",
                    ),
                ),
                (
                    "size_bytes",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="størrelse i byte"
                    ),
                ),
                (
                    "sha256",
                    models.CharField(
                        blank=True,
                        help_text="64 heksadesimale tegn når kjent.",
                        max_length=64,
                        verbose_name="SHA-256",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("raw_digitization", "Rå digitalisering"),
                            ("edited_wav_master", "Redigert WAV-master"),
                            ("radio_flac", "Radio-FLAC"),
                            ("distribution", "Distribusjonsfil"),
                            ("cover_image", "Cover/bilde"),
                            ("document", "Dokument"),
                            ("other", "Annen mediefil"),
                        ],
                        max_length=30,
                        verbose_name="filrolle",
                    ),
                ),
                (
                    "technical_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="tekniske metadata",
                    ),
                ),
                (
                    "recording",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="file_assets",
                        to="catalogue.recording",
                        verbose_name="innspilling",
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="file_assets",
                        to="catalogue.release",
                        verbose_name="utgivelse",
                    ),
                ),
            ],
            options={
                "verbose_name": "filressurs",
                "verbose_name_plural": "filressurser",
                "ordering": ("filename", "id"),
            },
        ),
        migrations.CreateModel(
            name="FileLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="opprettet"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="sist endret"
                    ),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "storage_type",
                    models.CharField(
                        choices=[
                            ("nas", "NAS"),
                            ("google_drive", "Google Drive"),
                            ("local", "Lokal lagring"),
                            ("cloud", "Annen skylagring"),
                            ("other", "Annen"),
                        ],
                        max_length=30,
                        verbose_name="lagringstype",
                    ),
                ),
                (
                    "relative_path",
                    models.CharField(
                        max_length=1000,
                        validators=[media_assets.models.validate_logical_path],
                        verbose_name="logisk relativ sti",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktiv"),
                            ("moved", "Flyttet"),
                            ("missing", "Mangler"),
                            ("historical", "Historisk"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True, verbose_name="nåværende plassering"
                    ),
                ),
                (
                    "observed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="observert"
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="avsluttet"
                    ),
                ),
                (
                    "google_drive_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Google Drive-ID",
                    ),
                ),
                (
                    "google_drive_url",
                    models.URLField(
                        blank=True,
                        max_length=1000,
                        verbose_name="Google Drive-URL",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locations",
                        to="media_assets.fileasset",
                        verbose_name="filressurs",
                    ),
                ),
            ],
            options={
                "verbose_name": "filplassering",
                "verbose_name_plural": "filplasseringer",
                "ordering": ("asset", "-is_current", "-observed_at"),
            },
        ),
        migrations.AddConstraint(
            model_name="fileasset",
            constraint=models.CheckConstraint(
                condition=models.Q(("filename__regex", ".*\\S.*")),
                name="file_asset_nonblank_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="fileasset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("recording__isnull", True),
                    ("release__isnull", True),
                    _connector="OR",
                ),
                name="file_asset_at_most_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="fileasset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sha256", ""), _negated=True),
                fields=("sha256",),
                name="file_asset_unique_sha256",
            ),
        ),
        migrations.AddIndex(
            model_name="filelocation",
            index=models.Index(
                fields=["storage_type", "relative_path"],
                name="file_location_path_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="filelocation",
            index=models.Index(
                fields=["status", "is_current"], name="file_location_state_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="filelocation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("asset", "storage_type", "relative_path"),
                name="file_location_unique_current_path",
            ),
        ),
    ]
