# Generated by Django 5.2.17 on 2026-09-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_assets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filelocation",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("unchecked", "Ikke kontrollert"),
                    ("verified", "Kontrollert plassering"),
                ],
                default="unchecked",
                max_length=20,
                verbose_name="kontrollstatus",
            ),
        ),
        migrations.AddIndex(
            model_name="filelocation",
            index=models.Index(
                fields=["verification_status"], name="file_location_verify_idx"
            ),
        ),
    ]
