# Generated by Django 5.2.17 on 2026-09-13 20:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalogue",
            "0005_remove_recordingcontribution_contribution_valid_role_and_more",
        ),
        ("media_assets", "0002_filelocation_verification_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileChecksum",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="opprettet"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="sist endret"),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                ("sha256", models.CharField(max_length=64, verbose_name="SHA-256")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("ingest", "Innlesing"),
                            ("writeback", "Etter metadataoppdatering"),
                            ("verification", "Kontroll"),
                        ],
                        max_length=20,
                        verbose_name="årsak",
                    ),
                ),
                (
                    "observed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="observert"),
                ),
            ],
            options={
                "verbose_name": "filkontrollsum",
                "verbose_name_plural": "filkontrollsummer",
                "ordering": ("-observed_at", "id"),
            },
        ),
        migrations.RemoveConstraint(
            model_name="fileasset",
            name="file_asset_at_most_one_target",
        ),
        migrations.RemoveConstraint(
            model_name="fileasset",
            name="file_asset_unique_sha256",
        ),
        migrations.RemoveConstraint(
            model_name="filelocation",
            name="file_location_unique_current_path",
        ),
        migrations.AddField(
            model_name="fileasset",
            name="metadata_read_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="filmetadata sist lest"
            ),
        ),
        migrations.AddField(
            model_name="fileasset",
            name="release_track",
            field=models.ForeignKey(
                blank=True,
                help_text="Brukes bare når filens utgivelseskontekst er entydig.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="file_assets",
                to="catalogue.releasetrack",
                verbose_name="spor på utgivelse",
            ),
        ),
        migrations.AddField(
            model_name="fileasset",
            name="source_modified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="fil sist endret"
            ),
        ),
        migrations.AddField(
            model_name="fileasset",
            name="sync_error",
            field=models.TextField(blank=True, verbose_name="synkroniseringsfeil"),
        ),
        migrations.AddField(
            model_name="fileasset",
            name="sync_requested_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="synkronisering bestilt"
            ),
        ),
        migrations.AddField(
            model_name="fileasset",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("not_applicable", "Ikke aktuell"),
                    ("synced", "Synkronisert"),
                    ("pending", "Venter på synkronisering"),
                    ("missing", "Fil ikke funnet"),
                    ("conflict", "Konflikt"),
                    ("failed", "Synkronisering feilet"),
                ],
                default="not_applicable",
                max_length=20,
                verbose_name="synkroniseringsstatus",
            ),
        ),
        migrations.AddField(
            model_name="fileasset",
            name="synced_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="synkronisert"
            ),
        ),
        migrations.AddConstraint(
            model_name="fileasset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("release_track__isnull", True),
                    models.Q(("recording__isnull", False), ("release__isnull", True)),
                    _connector="OR",
                ),
                name="file_track_requires_recording",
            ),
        ),
        migrations.AddConstraint(
            model_name="fileasset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("recording__isnull", True),
                    ("release__isnull", True),
                    _connector="OR",
                ),
                name="file_asset_no_recording_release_pair",
            ),
        ),
        migrations.AddIndex(
            model_name="fileasset",
            index=models.Index(
                fields=["role", "sync_status"], name="file_asset_sync_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="filelocation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("storage_type", "relative_path"),
                name="file_location_unique_current_path",
            ),
        ),
        migrations.AddField(
            model_name="filechecksum",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="checksum_history",
                to="media_assets.fileasset",
                verbose_name="filressurs",
            ),
        ),
        migrations.AddConstraint(
            model_name="filechecksum",
            constraint=models.UniqueConstraint(
                fields=("asset", "sha256"), name="file_checksum_unique_value"
            ),
        ),
    ]
