# Generated by Django 5.2.17 on 2026-09-15 13:53

import django.db.models.deletion
import media_assets.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalogue",
            "0005_remove_recordingcontribution_contribution_valid_role_and_more",
        ),
        ("media_assets", "0003_filechecksum_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileDerivation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="opprettet"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="sist endret"
                    ),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[("generated_from", "Generert fra")],
                        default="generated_from",
                        max_length=30,
                    ),
                ),
                ("tool_name", models.CharField(max_length=100)),
                ("tool_version", models.CharField(blank=True, max_length=100)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("verification", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "filavledning",
                "verbose_name_plural": "filavledninger",
            },
        ),
        migrations.CreateModel(
            name="MediaAssetEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="opprettet"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="sist endret"
                    ),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("master_registered", "Master registrert"),
                            ("master_selected", "Master valgt"),
                            ("candidate_generated", "Kandidat generert"),
                            ("audio_verified", "Lyd verifisert"),
                            ("metadata_verified", "Metadata verifisert"),
                            ("radio_activated", "Radiofil aktivert"),
                            ("radio_superseded", "Radiofil avløst"),
                        ],
                        max_length=30,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "mediefilhendelse",
                "verbose_name_plural": "mediefilhendelser",
                "ordering": ("-created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="RadioFlacGeneration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="opprettet"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="sist endret"
                    ),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                ("target_root_key", models.CharField(max_length=100)),
                (
                    "target_relative_path",
                    models.CharField(
                        max_length=1000,
                        validators=[media_assets.models.validate_logical_path],
                    ),
                ),
                ("technical_plan", models.JSONField(default=dict)),
                ("expected_tags", models.JSONField(default=dict)),
                ("metadata_diff", models.JSONField(default=list)),
                ("verification", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planlagt"),
                            ("verified", "Generert og verifisert"),
                            ("activated", "Aktivert"),
                            ("failed", "Feilet"),
                        ],
                        max_length=20,
                    ),
                ),
                ("failure_message", models.TextField(blank=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "radio-FLAC-generering",
                "verbose_name_plural": "radio-FLAC-genereringer",
                "ordering": ("-created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="RecordingMediaSelection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="opprettet"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="sist endret"
                    ),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "selected_master_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "current_radio_at",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "medievalg for innspilling",
                "verbose_name_plural": "medievalg for innspillinger",
            },
        ),
        migrations.RemoveConstraint(
            model_name="filelocation",
            name="file_location_unique_current_path",
        ),
        migrations.AddField(
            model_name="fileasset",
            name="lifecycle_status",
            field=models.CharField(
                choices=[
                    ("unclassified", "Ikke klassifisert"),
                    ("candidate", "Kandidat"),
                    ("current", "Gjeldende"),
                    ("historical", "Historisk"),
                ],
                default="unclassified",
                max_length=20,
                verbose_name="livssyklusstatus",
            ),
        ),
        migrations.AddField(
            model_name="filelocation",
            name="storage_root_key",
            field=models.CharField(
                blank=True,
                help_text="Tom verdi bruker kompatibilitetsmapping fra lagringstype.",
                max_length=100,
                verbose_name="storage-root",
            ),
        ),
        migrations.AddConstraint(
            model_name="fileasset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("lifecycle_status__in", ("unclassified", "historical")),
                    models.Q(
                        ("recording__isnull", False), ("role", "radio_flac")
                    ),
                    _connector="OR",
                ),
                name="file_asset_active_lifecycle_is_radio",
            ),
        ),
        migrations.AddConstraint(
            model_name="fileasset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("lifecycle_status", "current")),
                fields=("recording",),
                name="file_asset_one_current_radio",
            ),
        ),
        migrations.AddConstraint(
            model_name="filelocation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("storage_root_key", "storage_type", "relative_path"),
                name="file_location_unique_current_path",
            ),
        ),
        migrations.AddField(
            model_name="filederivation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="file_derivations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="filederivation",
            name="derived_asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="source_files",
                to="media_assets.fileasset",
            ),
        ),
        migrations.AddField(
            model_name="filederivation",
            name="source_asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="derived_files",
                to="media_assets.fileasset",
            ),
        ),
        migrations.AddField(
            model_name="mediaassetevent",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="media_asset_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mediaassetevent",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="media_events",
                to="media_assets.fileasset",
            ),
        ),
        migrations.AddField(
            model_name="mediaassetevent",
            name="recording",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="media_events",
                to="catalogue.recording",
            ),
        ),
        migrations.AddField(
            model_name="mediaassetevent",
            name="related_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="related_media_events",
                to="media_assets.fileasset",
            ),
        ),
        migrations.AddField(
            model_name="radioflacgeneration",
            name="activated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activated_radio_flac_generations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="radioflacgeneration",
            name="candidate_asset",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="generation",
                to="media_assets.fileasset",
            ),
        ),
        migrations.AddField(
            model_name="radioflacgeneration",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="radio_flac_generations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="radioflacgeneration",
            name="master_asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="master_generations",
                to="media_assets.fileasset",
            ),
        ),
        migrations.AddField(
            model_name="radioflacgeneration",
            name="radio_metadata_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="metadata_source_generations",
                to="media_assets.fileasset",
            ),
        ),
        migrations.AddField(
            model_name="radioflacgeneration",
            name="recording",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="radio_flac_generations",
                to="catalogue.recording",
            ),
        ),
        migrations.AddField(
            model_name="recordingmediaselection",
            name="current_radio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="current_for_recordings",
                to="media_assets.fileasset",
                verbose_name="gjeldende radiofil",
            ),
        ),
        migrations.AddField(
            model_name="recordingmediaselection",
            name="current_radio_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="selected_current_radio_files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recordingmediaselection",
            name="recording",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="media_selection",
                to="catalogue.recording",
                verbose_name="innspilling",
            ),
        ),
        migrations.AddField(
            model_name="recordingmediaselection",
            name="selected_master",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="selected_for_recordings",
                to="media_assets.fileasset",
                verbose_name="valgt master",
            ),
        ),
        migrations.AddField(
            model_name="recordingmediaselection",
            name="selected_master_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="selected_media_masters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="filederivation",
            constraint=models.UniqueConstraint(
                fields=("source_asset", "derived_asset", "relation_type"),
                name="file_derivation_unique_relation",
            ),
        ),
    ]
