# Generated by Django 5.2.17 on 2026-09-15 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalogue",
            "0005_remove_recordingcontribution_contribution_valid_role_and_more",
        ),
        (
            "media_assets",
            "0004_filederivation_mediaassetevent_radioflacgeneration_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="radioflacgeneration",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planlagt"),
                    ("generating", "Generering pågår"),
                    ("verified", "Generert og verifisert"),
                    ("activated", "Aktivert"),
                    ("failed", "Feilet"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="filederivation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_asset", models.F("derived_asset")), _negated=True
                ),
                name="file_derivation_not_self",
            ),
        ),
        migrations.AddConstraint(
            model_name="radioflacgeneration",
            constraint=models.UniqueConstraint(
                fields=("target_root_key", "target_relative_path"),
                name="radio_generation_unique_target",
            ),
        ),
    ]
