# Generated by Django 5.2.17 on 2026-09-15 18:07

import django.db.models.deletion
import rights_core.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalogue",
            "0005_remove_recordingcontribution_contribution_valid_role_and_more",
        ),
        ("media_assets", "0005_harden_master_lifecycle_invariants"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaassetevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("master_registered", "Master registrert"),
                    ("master_selected", "Master valgt"),
                    ("candidate_generated", "Kandidat generert"),
                    ("audio_verified", "Lyd verifisert"),
                    ("metadata_verified", "Metadata verifisert"),
                    ("radio_activated", "Radiofil aktivert"),
                    ("radio_superseded", "Radiofil avløst"),
                    (
                        "digitization_registered",
                        "Digitaliseringsfil registrert",
                    ),
                    ("raw_linked", "Råkilde koblet"),
                    ("recording_linked", "Master koblet til innspilling"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="mediaassetevent",
            name="recording",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="media_events",
                to="catalogue.recording",
            ),
        ),
        migrations.CreateModel(
            name="DigitizationBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="opprettet"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="sist endret"
                    ),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255,
                        validators=[rights_core.models.validate_not_blank],
                        verbose_name="navn på digitalisering",
                    ),
                ),
                (
                    "captured_on",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="digitaliseringsdato",
                    ),
                ),
                (
                    "source_description",
                    models.TextField(
                        blank=True, verbose_name="kildebeskrivelse"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="merknad"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Under arbeid"),
                            ("complete", "Avsluttet"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="digitization_batches",
                        to="catalogue.release",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
                "permissions": [
                    (
                        "operate_digitization",
                        "Utføre kontrollerte digitaliseringsoperasjoner",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="mediaassetevent",
            name="digitization_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="media_assets.digitizationbatch",
            ),
        ),
        migrations.CreateModel(
            name="DigitizationFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="opprettet"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="sist endret"
                    ),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "registration_key",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="digitization_file",
                        to="media_assets.fileasset",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="files",
                        to="media_assets.digitizationbatch",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DigitizationPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="opprettet"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="sist endret"
                    ),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                ("operation", models.CharField(max_length=30)),
                ("payload", models.JSONField(default=dict)),
                ("expected_state", models.CharField(max_length=64)),
                ("consequences", models.JSONField(default=list)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plans",
                        to="media_assets.digitizationbatch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DigitizationDerivation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="opprettet"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="sist endret"
                    ),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("note", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "derived_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="digitization_sources",
                        to="media_assets.fileasset",
                    ),
                ),
                (
                    "source_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="digitization_outputs",
                        to="media_assets.fileasset",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("source_asset", models.F("derived_asset")),
                            _negated=True,
                        ),
                        name="digitization_not_self",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("derived_asset",),
                        name="digitization_one_active_source",
                    ),
                ],
            },
        ),
    ]
