# Generated by Django 5.2.17 on 2026-09-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_assets", "0006_digitization_pipeline"),
    ]

    operations = [
        migrations.AddField(
            model_name="radioflacgeneration",
            name="database_metadata_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
