# Generated by Django 5.2.17 on 2026-09-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media_assets", "0008_backfill_unambiguous_current_radio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaassetevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("master_registered", "Master registrert"),
                    ("master_selected", "Master valgt"),
                    ("candidate_generated", "Kandidat generert"),
                    ("audio_verified", "Lyd verifisert"),
                    ("metadata_verified", "Metadata verifisert"),
                    ("radio_activated", "Radiofil aktivert"),
                    ("radio_superseded", "Radiofil avløst"),
                    (
                        "digitization_registered",
                        "Digitaliseringsfil registrert",
                    ),
                    ("raw_linked", "Råkilde koblet"),
                    ("raw_unlinked", "Råkildekobling fjernet"),
                    (
                        "recording_linked",
                        "Master koblet til innspilling",
                    ),
                    (
                        "recording_unlinked",
                        "Masterkobling til innspilling fjernet",
                    ),
                    ("master_selection_cleared", "Mastervalg fjernet"),
                ],
                max_length=30,
            ),
        ),
    ]
