# Generated by Django 5.2.17 on 2026-09-23 19:02

import django.db.models.deletion
import media_assets.digitization_configuration
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_assets", "0009_alter_mediaassetevent_event_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitizationConfiguration",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("raw_root_key", models.CharField(max_length=50)),
                ("raw_base_path", models.CharField(default=".", max_length=1000)),
                (
                    "raw_folder_template",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        validators=[
                            media_assets.digitization_configuration.validate_folder_template
                        ],
                    ),
                ),
                ("master_root_key", models.CharField(max_length=50)),
                ("master_base_path", models.CharField(default=".", max_length=1000)),
                (
                    "master_folder_template",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        validators=[
                            media_assets.digitization_configuration.validate_folder_template
                        ],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "digitaliseringsinnstilling",
                "verbose_name_plural": "digitaliseringsinnstillinger",
            },
        ),
    ]
