# Generated by Django 5.2.17 on 2026-09-13 13:10

import django.db.models.deletion
import rights_core.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="opprettet"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="sist endret"),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "external_batch_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ekstern batch-ID"
                    ),
                ),
                (
                    "imported_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="importert"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="merknader")),
            ],
            options={
                "verbose_name": "importbatch",
                "verbose_name_plural": "importbatcher",
                "ordering": ("-imported_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="MetadataAssertion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="opprettet"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="sist endret"),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("recording", "Innspilling"),
                            ("release", "Utgivelse"),
                            ("release_track", "Spor på utgivelse"),
                            ("party", "Person/organisasjon"),
                            ("artist_identity", "Artistidentitet"),
                            ("label", "Label"),
                            ("music_library_entry", "Musikkarkivpost"),
                            ("managed_recording", "Forvaltet innspilling"),
                            ("file_asset", "Filressurs"),
                        ],
                        max_length=40,
                        verbose_name="objekttype",
                    ),
                ),
                (
                    "entity_uuid",
                    models.UUIDField(db_index=True, verbose_name="objektets UUID"),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="Stabilt teknisk feltnavn, for eksempel release_year.",
                        max_length=100,
                        verbose_name="feltnavn",
                    ),
                ),
                ("raw_value", models.TextField(verbose_name="original kildeverdi")),
                (
                    "normalized_value",
                    models.JSONField(
                        blank=True, null=True, verbose_name="normalisert verdi"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unverified", "Importert / ikke verifisert"),
                            ("confirmed", "Bekreftet"),
                            ("disputed", "Bestridt"),
                            ("rejected", "Avvist"),
                            ("superseded", "Erstattet"),
                        ],
                        default="unverified",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="provenance.metadataassertion",
                        verbose_name="erstatter påstand",
                    ),
                ),
            ],
            options={
                "verbose_name": "metadatapåstand",
                "verbose_name_plural": "metadatapåstander",
                "ordering": (
                    "status",
                    "entity_type",
                    "entity_uuid",
                    "field_name",
                    "-created_at",
                ),
            },
        ),
        migrations.CreateModel(
            name="AssertionDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="opprettet"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="sist endret"),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("confirmed", "Bekreftet"),
                            ("disputed", "Bestridt"),
                            ("rejected", "Avvist"),
                            ("superseded", "Erstattet"),
                        ],
                        max_length=20,
                        verbose_name="avgjørelse",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="begrunnelse")),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="metadata_decisions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="avgjort av",
                    ),
                ),
                (
                    "assertion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="provenance.metadataassertion",
                        verbose_name="metadatapåstand",
                    ),
                ),
            ],
            options={
                "verbose_name": "metadataavgjørelse",
                "verbose_name_plural": "metadataavgjørelser",
                "ordering": ("-created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="SourceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="opprettet"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="sist endret"),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "external_record_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ekstern post-ID"
                    ),
                ),
                (
                    "source_locator",
                    models.CharField(
                        blank=True,
                        help_text="For eksempel LP-cover eller filnavn.",
                        max_length=500,
                        verbose_name="kildehenvisning",
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Bevares uendret som kildespor.",
                        verbose_name="originale kildedata",
                    ),
                ),
                (
                    "import_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_records",
                        to="provenance.importbatch",
                        verbose_name="importbatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "kildepost",
                "verbose_name_plural": "kildeposter",
                "ordering": ("source_system", "external_record_id", "id"),
            },
        ),
        migrations.AddField(
            model_name="metadataassertion",
            name="source_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assertions",
                to="provenance.sourcerecord",
                verbose_name="kildepost",
            ),
        ),
        migrations.CreateModel(
            name="SourceSystem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="opprettet"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="sist endret"),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        validators=[rights_core.models.validate_not_blank],
                        verbose_name="navn",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("manual", "Manuell registrering"),
                            ("physical", "Fysisk kilde"),
                            ("import", "Filimport"),
                            ("api", "Eksternt system/API"),
                            ("other", "Annen"),
                        ],
                        max_length=20,
                        verbose_name="kildetype",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="beskrivelse"),
                ),
            ],
            options={
                "verbose_name": "kildesystem",
                "verbose_name_plural": "kildesystemer",
                "ordering": ("name", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name",), name="source_system_unique_name"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("name__regex", ".*\\S.*")),
                        name="source_system_nonblank_name",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="sourcerecord",
            name="source_system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="source_records",
                to="provenance.sourcesystem",
                verbose_name="kildesystem",
            ),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="source_system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="import_batches",
                to="provenance.sourcesystem",
                verbose_name="kildesystem",
            ),
        ),
        migrations.AddIndex(
            model_name="metadataassertion",
            index=models.Index(
                fields=["entity_type", "entity_uuid", "field_name"],
                name="assertion_target_field_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="metadataassertion",
            index=models.Index(fields=["status"], name="assertion_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="metadataassertion",
            constraint=models.CheckConstraint(
                condition=models.Q(("field_name__regex", "^[a-z][a-z0-9_]*$")),
                name="assertion_valid_field_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcerecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_record_id", ""), _negated=True),
                fields=("source_system", "external_record_id"),
                name="source_record_unique_external_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_batch_id", ""), _negated=True),
                fields=("source_system", "external_batch_id"),
                name="import_batch_unique_external_id",
            ),
        ),
    ]
