# Generated by Django 5.2.17 on 2026-09-13 14:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provenance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppliedMetadataChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="opprettet"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="sist endret"
                    ),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("recording", "Innspilling"),
                            ("release", "Utgivelse"),
                            ("release_track", "Spor på utgivelse"),
                            ("party", "Person/organisasjon"),
                            ("artist_identity", "Artistidentitet"),
                            ("label", "Label"),
                            ("music_library_entry", "Musikkarkivpost"),
                            ("managed_recording", "Forvaltet innspilling"),
                            ("file_asset", "Filressurs"),
                        ],
                        max_length=40,
                        verbose_name="objekttype",
                    ),
                ),
                (
                    "entity_uuid",
                    models.UUIDField(
                        db_index=True, verbose_name="objektets UUID"
                    ),
                ),
                (
                    "field_name",
                    models.CharField(max_length=100, verbose_name="feltnavn"),
                ),
                (
                    "before_value",
                    models.JSONField(
                        blank=True, null=True, verbose_name="tidligere verdi"
                    ),
                ),
                (
                    "after_value",
                    models.JSONField(
                        blank=True, null=True, verbose_name="ny verdi"
                    ),
                ),
                (
                    "base_revision",
                    models.PositiveBigIntegerField(
                        verbose_name="forventet revisjon"
                    ),
                ),
                (
                    "result_revision",
                    models.PositiveBigIntegerField(verbose_name="ny revisjon"),
                ),
                (
                    "assertion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applied_changes",
                        to="provenance.metadataassertion",
                        verbose_name="metadatapåstand",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applied_metadata_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="endret av",
                    ),
                ),
            ],
            options={
                "verbose_name": "anvendt kildeverdi",
                "verbose_name_plural": "anvendte kildeverdier",
                "ordering": ("-created_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_uuid", "field_name"],
                        name="applied_change_target_idx",
                    )
                ],
            },
        ),
    ]
