# Generated by Django 5.2.17 on 2026-09-13 12:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("music_library", "0001_initial"),
        ("provenance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagedRecording",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="opprettet"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="sist endret"
                    ),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Til vurdering"),
                            ("active", "Aktiv forvaltning"),
                            ("inactive", "Ikke aktiv"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="forvaltningsstatus",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="merknader"),
                ),
                (
                    "library_entry",
                    models.OneToOneField(
                        help_text="Databasekoblingen sikrer at forvaltet musikk alltid finnes i Musikkarkivet.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="managed_recording",
                        to="music_library.musiclibraryentry",
                        verbose_name="musikkarkivpost",
                    ),
                ),
                (
                    "source_system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="managed_recordings",
                        to="provenance.sourcesystem",
                        verbose_name="kilde",
                    ),
                ),
            ],
            options={
                "verbose_name": "forvaltet innspilling",
                "verbose_name_plural": "forvaltet musikk",
                "ordering": ("library_entry__recording__title", "id"),
                "indexes": [
                    models.Index(fields=["status"], name="managed_status_idx")
                ],
            },
        ),
    ]
