# Generated by Django 5.2.17 on 2026-09-15 20:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalogue",
            "0005_remove_recordingcontribution_contribution_valid_role_and_more",
        ),
        ("managed_music", "0001_initial"),
        ("provenance", "0002_appliedmetadatachange"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagedRelease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="permanent UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="opprettet"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="sist endret"),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=1, editable=False, verbose_name="revisjon"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Til vurdering"),
                            ("active", "Aktiv forvaltning"),
                            ("inactive", "Ikke aktiv"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="forvaltningsstatus",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("owned_catalogue", "Eid/kontrollert katalog"),
                            ("managed_catalogue", "Forvaltet på vegne av andre"),
                        ],
                        help_text="Gjelder utgivelsen som katalogobjekt og sier ikke hvem som eier masterne på sporene.",
                        max_length=30,
                        verbose_name="katalogforhold",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="merknader")),
                (
                    "release",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="managed_release",
                        to="catalogue.release",
                        verbose_name="utgivelse",
                    ),
                ),
                (
                    "source_system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="managed_releases",
                        to="provenance.sourcesystem",
                        verbose_name="kilde",
                    ),
                ),
            ],
            options={
                "verbose_name": "forvaltet utgivelse",
                "verbose_name_plural": "forvaltede utgivelser",
                "ordering": ("release__title", "id"),
                "indexes": [
                    models.Index(fields=["status"], name="managed_release_status_idx"),
                    models.Index(
                        fields=["relationship"], name="managed_release_rel_idx"
                    ),
                ],
            },
        ),
    ]
